spring:
  application:
    name: ${artifactId}
  profiles:
    active: local
swagger:
  base-package: ${basePackage}.controller
  info:
    title: ${artifactId}
server:
  error:
    include-stacktrace: always
    include-exception: true
logging:
  file: <%='logs/${spring.application.name}.log'%>
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
